"use client";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Scale, Plus, Trash2, FileDown, Loader2, BookOpen } from "lucide-react";
import { search, createDraft, type Language, type SearchResult } from "@/lib/api";
import { useLanguage } from "@/lib/useLanguage";
import CitationCard from "@/components/CitationCard";
import ReactMarkdown from "react-markdown";
import Link from "next/link";

interface CaseSection {
  id: string;
  heading: string;
  query: string;
  result: SearchResult | null;
  loading: boolean;
}

const NAV_LINKS = [
  { href: "/laws", label_mt: "Liġijiet", label_en: "Laws" },
  { href: "/judgments", label_mt: "Sentenzi", label_en: "Judgments" },
  { href: "/lawyers", label_mt: "Avukati", label_en: "Lawyers" },
  { href: "/documents", label_mt: "Dokumenti", label_en: "Documents" },
  { href: "/draft", label_mt: "Abbozza", label_en: "Draft" },
  { href: "/case-builder", label_mt: "Ibni Każ", label_en: "Build Case" },
];

export default function CaseBuilderPage() {
  const [lang, setLang] = useLanguage();
  const [caseName, setCaseName] = useState("");
  const [sections, setSections] = useState<CaseSection[]>([
    { id: "1", heading: lang === "mt" ? "Fatti Rilevanti" : "Relevant Facts", query: "", result: null, loading: false },
    { id: "2", heading: lang === "mt" ? "Bażi Legali" : "Legal Basis", query: "", result: null, loading: false },
    { id: "3", heading: lang === "mt" ? "Preċedenti Rilevanti" : "Relevant Precedents", query: "", result: null, loading: false },
  ]);
  const [exporting, setExporting] = useState(false);

  const updateSection = (id: string, updates: Partial<CaseSection>) => {
    setSections((s) => s.map((sec) => sec.id === id ? { ...sec, ...updates } : sec));
  };

  const researchSection = async (section: CaseSection) => {
    if (!section.query.trim()) return;
    updateSection(section.id, { loading: true, result: null });
    try {
      const result = await search(section.query, lang);
      updateSection(section.id, { result, loading: false });
    } catch {
      updateSection(section.id, { loading: false });
    }
  };

  const addSection = () => {
    const newId = Date.now().toString();
    setSections((s) => [...s, {
      id: newId,
      heading: lang === "mt" ? "Taqsima Ġdida" : "New Section",
      query: "",
      result: null,
      loading: false,
    }]);
  };

  const removeSection = (id: string) => {
    setSections((s) => s.filter((sec) => sec.id !== id));
  };

  const exportCase = async () => {
    if (!caseName.trim()) return;
    setExporting(true);
    try {
      // Try backend DOCX generation first
      try {
        const instructions = sections
          .filter((s) => s.result)
          .map((s) => `## ${s.heading}\n\n${s.result!.answer}\n\n**Sorsi:**\n${
            s.result!.sources.map((src, i) => `[${i+1}] ${src.title} — ${src.url}`).join("\n")
          }`)
          .join("\n\n---\n\n");
        const res = await createDraft("legal_opinion", `Case: ${caseName}\n\n${instructions}`, lang);
        const url = URL.createObjectURL(res.data);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${caseName.replace(/\s+/g, "_")}_${lang}.docx`;
        a.click();
        URL.revokeObjectURL(url);
        return;
      } catch {
        // Backend unavailable — fall back to HTML export
      }

      // Client-side fallback: export as styled HTML file (opens in Word/LibreOffice)
      const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<title>${caseName}</title>
<style>
  body { font-family: 'Times New Roman', serif; max-width: 800px; margin: 40px auto; line-height: 1.6; color: #1a1a2e; }
  h1 { text-align: center; border-bottom: 2px solid #d4a853; padding-bottom: 10px; }
  h2 { color: #4c9ac9; margin-top: 30px; border-bottom: 1px solid #e5e0d5; padding-bottom: 5px; }
  .sources { background: #f9f7f3; border: 1px solid #e5e0d5; border-radius: 8px; padding: 12px 16px; margin-top: 12px; }
  .sources p { font-size: 13px; margin: 4px 0; color: #6b7280; }
  .footer { text-align: center; font-size: 11px; color: #9ca3af; margin-top: 40px; border-top: 1px solid #e5e0d5; padding-top: 10px; }
</style></head><body>
<h1>${caseName}</h1>
<p style="text-align:center;color:#9ca3af;font-size:13px;">${lang === "mt" ? "Ġenerat minn" : "Generated by"} SacLigi — ${new Date().toLocaleDateString()}</p>
${sections.filter(s => s.result).map(s => `
<h2>${s.heading}</h2>
<div>${s.result!.answer.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>')}</div>
${s.result!.sources.length > 0 ? `<div class="sources">
<p><strong>${lang === "mt" ? "Sorsi" : "Sources"}:</strong></p>
${s.result!.sources.map((src, i) => `<p>[${i+1}] ${src.title} — <a href="${src.url}">${src.url}</a></p>`).join("")}
</div>` : ""}
`).join("\n<hr>\n")}
<div class="footer">
<p>SacLigi — ${lang === "mt" ? "Il-Liġi Maltija Miftuħa għal Kulħadd" : "Free Maltese Legal Intelligence"}</p>
<p>Powered by Rark Musso</p>
</div>
</body></html>`;

      const blob = new Blob([html], { type: "application/vnd.ms-word;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${caseName.replace(/\s+/g, "_")}_${lang}.doc`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      console.error(e);
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="min-h-screen bg-cream text-[#1a1a2e]">
      {/* Nav */}
      <nav className="sticky top-0 z-50 bg-white/90 backdrop-blur-xl border-b border-[#e5e0d5] shadow-sm">
        <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <Scale size={20} className="text-gold" />
            <span className="text-lg font-display font-bold text-[#1a1a2e]">
              <span className="text-gold">Sac</span>Ligi
            </span>
          </Link>
          <div className="hidden lg:flex items-center gap-6 text-sm text-[#6b7280]">
            {NAV_LINKS.map((link) => (
              <Link key={link.href} href={link.href}
                className="hover:text-gold transition-colors font-medium">
                {lang === "mt" ? link.label_mt : link.label_en}
              </Link>
            ))}
          </div>
          <button
            onClick={() => setLang(lang === "mt" ? "en" : "mt")}
            className="px-3 py-1.5 rounded-full border border-[#e5e0d5] hover:border-gold/50
                       hover:bg-gold/5 text-xs font-mono text-[#6b7280] transition-all"
          >
            {lang === "mt" ? "EN" : "MT"}
          </button>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-4 py-10">
        <div className="flex items-center justify-between mb-8">
          <Link href="/" className="text-sm text-[#9ca3af] hover:text-[#6b7280]">← Lura / Back</Link>
        </div>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <div className="flex items-center gap-3 mb-2">
            <Scale size={28} className="text-gold" />
            <h1 className="text-3xl font-display font-bold text-[#1a1a2e]">
              {lang === "mt" ? "Ibni l-Każ Tiegħek" : "Build Your Case"}
            </h1>
          </div>
          <p className="text-[#9ca3af] text-sm mb-8">
            {lang === "mt"
              ? "Kull sezzjoni tibni fuq l-oħra. Kull dikjarazzjoni ċċitata. Esporta bħala DOCX."
              : "Each section builds on the last. Every claim cited. Export as DOCX."}
          </p>

          {/* Case name */}
          <input
            value={caseName}
            onChange={(e) => setCaseName(e.target.value)}
            placeholder={lang === "mt" ? "Isem il-kawża / matters..." : "Case name / matter..."}
            className="w-full bg-white border border-[#e5e0d5] rounded-2xl px-5 py-4 mb-8 text-lg font-medium
                       focus:outline-none focus:border-gold/50 placeholder:text-[#9ca3af] transition-all text-[#1a1a2e]"
          />

          {/* Sections */}
          <div className="flex flex-col gap-6">
            {sections.map((section, idx) => (
              <motion.div
                key={section.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.05 }}
                className="bg-white border border-[#e5e0d5] rounded-2xl overflow-hidden shadow-sm"
              >
                {/* Section header */}
                <div className="flex items-center gap-3 px-5 py-4 border-b border-[#e5e0d5] bg-cream/60">
                  <span className="w-7 h-7 rounded-full bg-gold/15 border border-gold/30
                                   text-gold text-xs font-bold flex items-center justify-center shrink-0">
                    {idx + 1}
                  </span>
                  <input
                    value={section.heading}
                    onChange={(e) => updateSection(section.id, { heading: e.target.value })}
                    className="flex-1 bg-transparent text-sm font-semibold focus:outline-none text-[#1a1a2e]"
                  />
                  {sections.length > 1 && (
                    <button onClick={() => removeSection(section.id)}
                      className="p-1.5 text-[#9ca3af] hover:text-red-500 transition-colors">
                      <Trash2 size={14} />
                    </button>
                  )}
                </div>

                <div className="p-5">
                  {/* Query input */}
                  <div className="flex gap-2 mb-4">
                    <input
                      value={section.query}
                      onChange={(e) => updateSection(section.id, { query: e.target.value })}
                      onKeyDown={(e) => e.key === "Enter" && researchSection(section)}
                      placeholder={lang === "mt" ? "Staqsi mistoqsija dwar din it-taqsima..." : "Research question for this section..."}
                      className="flex-1 bg-cream border border-[#e5e0d5] rounded-xl px-4 py-3 text-sm
                                 focus:outline-none focus:border-gold/40 placeholder:text-[#9ca3af] text-[#1a1a2e]"
                    />
                    <button
                      onClick={() => researchSection(section)}
                      disabled={section.loading || !section.query.trim()}
                      className="px-4 py-3 bg-gold hover:bg-gold/90 text-white font-semibold
                                 rounded-xl transition-all disabled:opacity-40 flex items-center gap-1.5 text-sm"
                    >
                      {section.loading
                        ? <Loader2 size={15} className="animate-spin" />
                        : <><BookOpen size={15} /> {lang === "mt" ? "Ibħes" : "Research"}</>}
                    </button>
                  </div>

                  {/* Result */}
                  <AnimatePresence>
                    {section.result && (
                      <motion.div initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }}>
                        <div className="prose prose-sm max-w-none mb-4 leading-relaxed text-[#1a1a2e]
                                        prose-headings:text-[#1a1a2e] prose-p:text-[#6b7280]">
                          <ReactMarkdown>{section.result.answer}</ReactMarkdown>
                        </div>
                        {section.result.sources?.length > 0 && (
                          <CitationCard
                            citations={section.result.sources.map((s) => ({
                              type: s.type as any,
                              title: s.title,
                              url: s.url,
                              score: s.score,
                            }))}
                            language={lang}
                            onOpen={(c) => {
                              // Route to internal detail pages where possible
                              const baseUrl = process.env.NODE_ENV === "production" ? "/ligi4friends" : "";
                              if (c.type === "law") {
                                const ch = c.title.split(" — ")[0]?.trim();
                                window.open(`${baseUrl}/detail?type=law&id=${encodeURIComponent(ch)}`, "_blank");
                              } else if (c.type === "judgment") {
                                const ref = c.title.split(" — ")[0]?.trim();
                                window.open(`${baseUrl}/detail?type=judgment&id=${encodeURIComponent(ref)}`, "_blank");
                              } else if ((c.type as string) === "lawyer") {
                                window.open(`${baseUrl}/detail?type=lawyer&id=${encodeURIComponent(c.title)}`, "_blank");
                              } else {
                                window.open(c.url, "_blank");
                              }
                            }}
                          />
                        )}
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              </motion.div>
            ))}
          </div>

          {/* Add section */}
          <button
            onClick={addSection}
            className="w-full mt-4 py-3 border border-dashed border-[#e5e0d5] hover:border-gold/40
                       rounded-2xl text-sm text-[#9ca3af] hover:text-[#6b7280] transition-all flex items-center justify-center gap-2"
          >
            <Plus size={16} /> {lang === "mt" ? "Żid Taqsima" : "Add Section"}
          </button>

          {/* Export */}
          <button
            onClick={exportCase}
            disabled={exporting || !caseName.trim() || !sections.some((s) => s.result)}
            className="w-full mt-6 py-4 bg-gradient-to-r from-gold to-gold/80
                       hover:from-gold/90 hover:to-gold text-white font-bold rounded-2xl
                       transition-all disabled:opacity-40 flex items-center justify-center gap-2
                       shadow-lg shadow-gold/15"
          >
            {exporting
              ? <><Loader2 size={18} className="animate-spin" /> {lang === "mt" ? "Qed jesporta..." : "Exporting..."}</>
              : <><FileDown size={18} /> {lang === "mt" ? "Esporta l-Każ Sħiħ (DOCX)" : "Export Full Case (DOCX)"}</>
            }
          </button>
          <p className="text-xs text-center text-[#9ca3af] mt-3">
            {lang === "mt"
              ? "Il-DOCX ikun fih il-każ kollu b'referenzi sħaħ f'kull dikjarazzjoni."
              : "The DOCX will contain the full case with complete references on every claim."}
          </p>
        </motion.div>

        {/* Footer */}
        <div className="py-10 mt-10 text-center text-xs text-[#9ca3af] border-t border-[#e5e0d5]">
          <p>SacLigi — Powered by Rark Musso · B&apos;Xejn għal Dejjem</p>
        </div>
      </div>
    </div>
  );
}
